import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.boxLogo}>
                <span>RACHAE</span>
            </div>

            <div className={styles.boxCalculator}>
                <div className={styles.boxInfos}>
                    <span>
                        Conta
                    </span>

                    <input type="text" />

                    <span>
                        Gorjeta (%)
                    </span>

                    <div className={styles.boxTips}>
                        <button>5%</button>
                        <button>10%</button>
                        <button>15%</button>
                        <button>20%</button>
                        <button>25%</button>
                        <input type="text" placeholder='CUSTOM' />
                    </div>

                    <span>
                        Número de Pessoas
                    </span>

                    <input type="text" />
                </div>

                <div className={styles.boxResults}>
                    <div className={styles.boxResultsInfos}>
                        <div className={styles.boxDescription}>
                            <span>Gorjeta</span>
                            <small>/ pessoa</small>
                        </div>

                        <div className={styles.boxValue}>
                            <span>5,00</span>
                        </div>
                    
                        <div className={styles.boxDescription}>
                            <span>Conta</span>
                            <small>/ pessoa</small>
                        </div>
                        
                        <div className={styles.boxValue}>
                            <span>999,00</span>
                        </div>
                    </div>

                    <div>
                        <div className={styles.boxReset}>
                            <button>reset</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}
